version: "3"

services:
    api:
        image: ghcr.io/gevlee/swallow-api:latest
        restart: unless-stopped
        volumes:
            - ./data/:/app/data/
    web:
        image: ghcr.io/gevlee/swallow-web:latest
        restart: unless-stopped
        depends_on:
            - api
        ports:
            - 5050:80