FROM node:lts-alpine3.11 AS node-build

COPY ./src/Gevlee.Swallow.Web /source/Gevlee.Swallow.Web
COPY ./src/Gevlee.Swallow.Api.Contract /source/Gevlee.Swallow.Api.Contract

WORKDIR /source/Gevlee.Swallow.Web
RUN rm -r node_modules
RUN ls -la

RUN npm install
ENV NODE_ENV='production'
RUN npm run compile

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

RUN export PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install -g Microsoft.Web.LibraryManager.Cli

COPY --from=node-build /source /source

WORKDIR /source/Gevlee.Swallow.Web

RUN /root/.dotnet/tools/libman restore
RUN dotnet restore
RUN dotnet build -c Release -o /build /p:SkipBuildContent=True

FROM build-env AS publish
RUN dotnet publish -c Release -o /publish /p:SkipBuildContent=True

FROM nginx:alpine AS final

COPY --from=publish /publish/wwwroot /var/www/web

RUN ls -la /var/www/web

COPY ./config/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
