version: "3"

services:
    api:
        build:
            dockerfile: Dockerfile.api
            context: .
        restart: unless-stopped
        volumes:
            - ./data/:/app/data/
    web:
        build:
            dockerfile: Dockerfile.web
            context: .
        restart: unless-stopped
        depends_on:
            - api
        ports:
            - 5050:80